name: Node.js CLI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: self-hosted

        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 16
          uses: actions/setup-node@v3
          with:
                node-version: 16
        - run: |
            cd server
            npm i
            cd ..
            cd client
            npm i
            npm run build
            mv dist/ ../server/static
            cd ..
            cd server
            nvm i 16
            pm2 stop 0
            pm2 start 0
            pm2 save
            sudo service nginx restart

